# Generated by Django 4.2.3 on 2023-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is_discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='price_with_discount'),
        ),
    ]
