# Generated by Django 4.2.3 on 2023-07-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_is_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='site_name')),
                ('logo', models.ImageField(upload_to='site_logo', verbose_name='logo')),
                ('site_description', models.TextField(verbose_name='site_description')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='whatsapp_number')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram_id')),
                ('instagram_id', models.CharField(max_length=50, verbose_name='instagram_id')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
    ]
