# Generated by Django 4.2.3 on 2023-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(upload_to='site_logo/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='whatsapp_number'),
        ),
    ]
