# Generated by Django 4.2.3 on 2023-07-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_aboutus_logo_alter_aboutus_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='whatsapp_number(no 0)'),
        ),
    ]
