# Generated by Django 4.2.3 on 2023-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_aboutus_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(verbose_name='price (rial)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='price_with_discount (rial)'),
        ),
    ]
