# Generated by Django 4.2.3 on 2023-07-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='pages.colors', verbose_name='رنگ'),
        ),
    ]
