# Generated by Django 4.2.3 on 2023-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='phone',
            field=models.CharField(default='09122222222', max_length=11, verbose_name='phone'),
        ),
    ]
