# Generated by Django 4.2.3 on 2023-07-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
