# Generated by Django 4.2.3 on 2023-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='code')),
                ('discount_percent', models.SmallIntegerField(default=0, verbose_name='discount_percent')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'DiscountCode',
                'verbose_name_plural': 'DiscountCodes',
            },
        ),
    ]
