# Generated by Django 4.2.3 on 2023-07-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_discountcode_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='total_price'),
        ),
    ]
