# Generated by Django 4.2.3 on 2023-07-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='order_total_price',
        ),
    ]
