# Generated by Django 4.2.3 on 2023-07-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_total_price_order_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total_price',
        ),
    ]
