# Generated by Django 4.2.3 on 2023-07-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_is_discount_and_more'),
        ('order', '0007_remove_order_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='pages.product', verbose_name='product'),
        ),
    ]
