# Generated by Django 4.2.3 on 2023-07-10 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_order_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='user_used',
            field=models.ManyToManyField(related_name='discount_code', to=settings.AUTH_USER_MODEL, verbose_name='user_used'),
        ),
    ]
