# Generated by Django 4.2.3 on 2023-07-10 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_discountcode_user_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='user_used',
            field=models.ManyToManyField(blank=True, null=True, related_name='discount_code', to=settings.AUTH_USER_MODEL, verbose_name='user_used'),
        ),
    ]
