# Generated by Django 4.2.3 on 2023-07-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='رنگ'),
        ),
    ]
